import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {runWebKit,selectedTask} from './package/linux-run.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),pins=JSON.parse(fs.readFileSync(path.join(here,'source-package.json')));
function fixture(){
 const facts={platform:'linux',arch:'x64',browser:'webkit',head:'563f3c13665347b2a8578110e519ebaf13f356e8',tree:'ad5f79ab358e7de04d3de52c45f697f7134dc573',clean:true,sourceFilesValid:true,playwright:'1.62.0',cache:'/ms-playwright',revisions:[['chromium','1234'],['firefox','1538'],['webkit','2336']]};
 const raw={browser:{engine:'webkit',version:'26.5'},execution:{complete:true,infrastructureErrors:[],actions:Array.from({length:184},()=>({status:'COMPLETED'})),semanticTests:Array.from({length:4},()=>({status:'PASS'}))},observations:Array(84).fill({}),menuResults:Array(41).fill({})};
 const calls=[];const io={inspect:()=>facts,reserve:()=>calls.push('reserve'),execute:t=>{calls.push(structuredClone(t));return {status:0,signal:null,error:null};},readReport:()=>JSON.stringify(raw),readIsolation:()=>JSON.stringify({head:facts.head,engine:'webkit',measuredVersion:'26.5',attempts:[],violations:[]}),save:r=>{calls.push('save');io.report=structuredClone(r);}};
 return {facts,raw,calls,io};
}
test('real conductor emits exactly one fixed WebKit task and full canonical report, not acceptance',()=>{
 const f=fixture(),r=runWebKit(f.io);
 assert.equal(r.code,'WEBKIT_DIAGNOSTIC_COMPLETE_NOT_ACCEPTANCE');assert.equal(r.exitCode,0);
 assert.deepEqual(f.calls,['reserve',{name:'responsive-webkit',args:['/package/linux-responsive.mjs'],cwd:'/candidate',timeout:900000,engine:'webkit',report:'/outputs/results/responsive-webkit.json'},'save']);
 assert.deepEqual(r.results.map(x=>x.name),['responsive-webkit']);
});
for(const [name,change] of [['browser',f=>f.facts.browser='chromium'],['head',f=>f.facts.head='a'.repeat(40)],['tree',f=>f.facts.tree='a'.repeat(40)],['dirty',f=>f.facts.clean=false],['source bytes',f=>f.facts.sourceFilesValid=false],['version',f=>f.facts.playwright='1.61.0'],['cache',f=>f.facts.cache='/tmp'],['revision',f=>f.facts.revisions[2][1]='2335']])test(`refuses ${name} before any child starts`,()=>{const f=fixture();change(f);const r=runWebKit(f.io);assert.equal(r.code,'SOURCE_INVALID');assert.equal(r.exitCode,1);assert.deepEqual(f.calls,[]);});
test('pre-existing results marker forbids another child',()=>{const f=fixture();f.io.reserve=()=>{throw Error('already exists');};const r=runWebKit(f.io);assert.equal(r.code,'MARKER_INVALID');assert.equal(r.exitCode,1);assert.deepEqual(f.calls,[]);});
for(const [name,p,code] of [['nonzero',{status:1},'CHILD_FAILED'],['deadline',{status:null,error:{code:'ETIMEDOUT'}},'CHILD_FAILED'],['signal',{status:null,signal:'SIGTERM'},'CHILD_FAILED'],['missing exit',{},'CHILD_FAILED']])test(`${name} retains failure record and never launches another task`,()=>{const f=fixture();f.io.execute=t=>{f.calls.push(t);return p;};const r=runWebKit(f.io);assert.equal(r.code,code);assert.equal(r.exitCode,1);assert.equal(f.calls.filter(x=>x?.name).length,1);assert.equal(f.calls.at(-1),'save');assert.equal(f.io.report.exitCode,1);});
for(const [name,change,code] of [['missing',f=>f.io.readReport=()=>{throw Error('ENOENT');},'REPORT_INVALID'],['truncated',f=>f.io.readReport=()=>'{','REPORT_INVALID'],['incomplete',f=>f.raw.execution.complete=false,'REPORT_INCOMPLETE'],['missing action',f=>f.raw.execution.actions.pop(),'REPORT_INCOMPLETE'],['infra',f=>f.raw.execution.infrastructureErrors.push('SYNTHETIC_PRIVATE'),'REPORT_INCOMPLETE'],['semantic fail',f=>f.raw.execution.semanticTests[0].status='FAIL','REPORT_INCOMPLETE'],['wrong report engine',f=>f.raw.browser.engine='firefox','REPORT_INCOMPLETE'],['isolation absent',f=>f.io.readIsolation=()=>{throw Error('ENOENT');},'REPORT_INVALID'],['network attempt',f=>f.io.readIsolation=()=>JSON.stringify({head:f.facts.head,engine:'webkit',measuredVersion:'26.5',attempts:[{}],violations:[]}),'REPORT_INCOMPLETE']])test(`${name} cannot become complete diagnostic; summary survives`,()=>{const f=fixture();change(f);const r=runWebKit(f.io);assert.equal(r.code,code);assert.equal(r.exitCode,1);assert.equal(f.calls.at(-1),'save');});
test('save failure is explicit, not successful collection',()=>{const f=fixture();f.io.save=()=>{throw Error('disk');};const r=runWebKit(f.io);assert.equal(r.code,'COLLECTION_FAILED');assert.equal(r.exitCode,1);});
test('caller cannot mutate subsequent task selection',()=>{const t=selectedTask();t.engine='firefox';t.args.push('/package/causal-browser.mjs');assert.deepEqual(selectedTask(),{name:'responsive-webkit',args:['/package/linux-responsive.mjs'],cwd:'/candidate',timeout:900000,engine:'webkit',report:'/outputs/results/responsive-webkit.json'});});
test('source pin includes the full unmodified canonical test and route matrix',()=>{for(const file of ['tests/audit/f2-01-responsive.test.mjs','fixtures/audit/site-contract.json'])assert.ok(pins.sourceFiles.some(f=>f.file===file&&f.mode==='100644'&&/^[0-9a-f]{40}$/.test(f.blob)&&/^[0-9a-f]{64}$/.test(f.sha256)));});
